SELECT T-ADHERENTS.nom,T_MESSAGES.message
FROM T_ADHERENTS,T_MESSAGES
WHERE T_ADHERENTS.id=T_MESSAGES.id_adherent
AND T_ADHERENT.nom = 'machin'.


SELECT T_ADHERENTS.nom, T_MESSAGES.texte
FROM T_ADHERENTS
INNER JOIN T_MESSAGES ON T_ADHERENTS.id=T_MESSAGES
WHERE T_ADHERENTS.nom = 'machin';

SELECT T_CATEGORIES.id,T_ARTICLES.id
FROM T_CATEGORIES
LEFT JOIN T_CATEGORIES ON T_ARTICLES.id=T_ARTICLES
WHERE T_ARTICLES.ID_CATEGORIES = T_ARTICLES.ID_ARTICLES