SELECT T-ADHERENTS.nom,T_MESSAGES.message
FROM T_ADHERENTS,T_MESSAGES
WHERE T_ADHERENTS.id=T_MESSAGES.id_adherent
AND T_ADHERENT.nom = 'machin'.


SELECT T_ADHERENTS.nom, T_MESSAGES.texte
FROM T_ADHERENTS
INNER JOIN T_MESSAGES ON T_ADHERENTS.id=T_MESSAGES
WHERE T_ADHERENTS.nom = 'machin';
